import { jsPDF } from "jspdf";

export function exportProgressPDF(user, dashboard) {
  const doc = new jsPDF();
  const today = new Date().toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });

  // Header
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("CodeArena Progress Report", 20, 20);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`${user?.username} — ${today}`, 20, 32);

  // Stats section
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Performance Summary", 20, 58);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);

  const stats = dashboard?.stats || {};
  const lines = [
    `Problems Solved: ${stats.solvedCount || 0}`,
    `Total Submissions: ${stats.attemptCount || 0}`,
    `Success Rate: ${stats.successRate || 0}%`,
    `Current Streak: ${stats.currentStreak || 0} days`,
    `Longest Streak: ${stats.longestStreak || 0} days`,
  ];

  lines.forEach((line, i) => {
    doc.text(line, 20, 70 + i * 10);
  });

  // Verdict breakdown
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Verdict Breakdown", 20, 130);

  const verdicts = stats.verdictBreakdown || {};
  Object.entries(verdicts).forEach(([v, count], i) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text(`${v}: ${count}`, 20, 142 + i * 10);
  });

  // Score trend
  if (dashboard?.scoreTrend?.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Recent Code Quality Scores", 20, 200);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);

    const scores = dashboard.scoreTrend
      .slice(-10)
      .map((s) => s.score)
      .join(", ");
    doc.text(`Last 10 scores: ${scores}`, 20, 212);

    const avg = Math.round(
      dashboard.scoreTrend.reduce((a, b) => a + b.score, 0) /
        dashboard.scoreTrend.length
    );
    doc.text(`Average quality score: ${avg}/10`, 20, 222);
  }

  // Weak patterns
  if (dashboard?.weakPatterns?.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Areas to Improve", 20, 245);

    dashboard.weakPatterns.forEach((p, i) => {
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);
      doc.text(
        `${i + 1}. ${p.pattern} (detected ${p.count}x)`,
        20,
        257 + i * 10
      );
    });
  }

  // Footer
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 280, 210, 17, "F");
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by CodeArena — Personal Interview Prep OS",
    20,
    290
  );

  doc.save(`codearena-report-${today.replace(/\s/g, "-")}.pdf`);
}